import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import { Header } from "/src/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Attorneyster",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="../assets/img/misc/icon.png" sizes="any" />
      </Head>
      <body className={`${inter.className} bg-darkBlue`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
